name: Aula 8 - CI
on:
  push:
    branches:
      - main

jobs:
  build-todo-app:
    name: Validações com testes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure nodejs
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    
    - name: Build and test
      run: |
        cd '.\Aula 5 - Mocha Chai e Testes Unitários\'
        npm install
        npm run test